import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { BlockchainService, GENESIS_HASH } from '../src/services/blockchain.service';
import { recomputeScores } from '../src/services/scoring.service';
import { hashIdentityNumber, lastFour } from '../src/services/identity.service';

const prisma = new PrismaClient();

const UPLOAD_ROOT = path.resolve(process.env.UPLOAD_DIR ?? './private-uploads');

/**
 * Writes a small placeholder file so uploaded-document features (viewing,
 * integrity checking) work end to end straight after seeding.
 */
function writePlaceholder(ngoId: string, label: string, ext = 'pdf') {
  const dir = path.join(UPLOAD_ROOT, ngoId);
  fs.mkdirSync(dir, { recursive: true });

  const fileName = `${label.toLowerCase()}-sample.${ext}`;
  const absolute = path.join(dir, fileName);
  const body = `Sample ${label} document for demonstration.\nGenerated by the seed script.\n`;
  fs.writeFileSync(absolute, body, 'utf8');

  return {
    storagePath: `${ngoId}/${fileName}`,
    hash: crypto.createHash('sha256').update(fs.readFileSync(absolute)).digest('hex'),
    sizeBytes: Buffer.byteLength(body),
    fileName
  };
}

/** Builds a document row, hashing the identity number when there is one. */
function documentRow(
  ngoId: string,
  docType: string,
  status: string,
  identityNumber?: string
) {
  const isImage = ['AADHAAR', 'PAN', 'VOTER_ID'].includes(docType);
  const file = writePlaceholder(ngoId, docType, isImage ? 'png' : 'pdf');

  return {
    ngoId,
    docType,
    numberHash: identityNumber ? hashIdentityNumber(identityNumber) : null,
    numberLast4: identityNumber ? lastFour(identityNumber) : null,
    fileName: file.fileName,
    storagePath: file.storagePath,
    mimeType: isImage ? 'image/png' : 'application/pdf',
    sizeBytes: file.sizeBytes,
    hash: file.hash,
    status,
    verifiedAt: status === 'VERIFIED' ? new Date() : null
  };
}

async function main() {
  console.log('Seeding NGO Impact Data Commons…');

  // Start from a clean uploads folder so stray files do not accumulate.
  fs.rmSync(UPLOAD_ROOT, { recursive: true, force: true });
  fs.mkdirSync(UPLOAD_ROOT, { recursive: true });

  await prisma.$transaction([
    prisma.notification.deleteMany(),
    prisma.passwordResetToken.deleteMany(),
    prisma.auditLog.deleteMany(),
    prisma.communityVerification.deleteMany(),
    prisma.projectEvidence.deleteMany(),
    prisma.whistleblowerReport.deleteMany(),
    prisma.transparencyScore.deleteMany(),
    prisma.fraudAlert.deleteMany(),
    prisma.donation.deleteMany(),
    prisma.blockchainBlock.deleteMany(),
    prisma.expense.deleteMany(),
    prisma.beneficiary.deleteMany(),
    prisma.project.deleteMany(),
    prisma.nGOActivity.deleteMany(),
    prisma.nGOCause.deleteMany(),
    prisma.nGOPaymentDetails.deleteMany(),
    prisma.govVerification.deleteMany(),
    prisma.nGODocument.deleteMany(),
    prisma.nGO.deleteMany(),
    prisma.user.deleteMany()
  ]);

  const pw = (plain: string) => bcrypt.hash(plain, 10);

  /* -- Accounts ---------------------------------------------------------- */
  const admin = await prisma.user.create({
    data: {
      email: 'admin@ngocommons.demo', password: await pw('Admin@123'),
      name: 'Platform Admin', role: 'ADMIN', phone: '9876543210'
    }
  });

  const ngoUser1 = await prisma.user.create({
    data: { email: 'ngo@ngocommons.demo', password: await pw('NGO@1234'), name: 'Ramesh Patil', role: 'NGO', phone: '9811122233' }
  });
  const ngoUser2 = await prisma.user.create({
    data: { email: 'ruraledu@ngocommons.demo', password: await pw('NGO@1234'), name: 'Lakshmi Rao', role: 'NGO', phone: '9822233344' }
  });
  const ngoUser3 = await prisma.user.create({
    data: { email: 'newngo@ngocommons.demo', password: await pw('NGO@1234'), name: 'Anita Sharma', role: 'NGO', phone: '9833344455' }
  });

  const donor = await prisma.user.create({
    data: { email: 'donor@ngocommons.demo', password: await pw('Donor@123'), name: 'Meera Iyer', role: 'DONOR', phone: '9988776655' }
  });
  await prisma.user.create({
    data: { email: 'public@ngocommons.demo', password: await pw('Public@123'), name: 'Citizen Observer', role: 'PUBLIC' }
  });

  /* -- Organisations ----------------------------------------------------- */
  const ngo1 = await prisma.nGO.create({
    data: {
      userId: ngoUser1.id,
      name: 'Hope Foundation India',
      description: 'We run after-school learning centres and daily meal programmes for children of daily-wage workers across Delhi.',
      presidentName: 'Dr. Ramesh Patil',
      regNum: 'DEL/2018/0019482',
      address: '14 Institutional Area, Lodhi Road',
      city: 'New Delhi', state: 'Delhi', district: 'New Delhi', pinCode: '110003',
      phone: '9811122233', email: 'contact@hopefoundation.demo',
      website: 'https://hopefoundation.demo',
      mission: 'Quality education and nutrition for every child.',
      areaOfWork: 'Education, Nutrition',
      establishedYear: 2015, employees: 28, volunteers: 120,
      status: 'VERIFIED', verifiedAt: new Date()
    }
  });

  const ngo2 = await prisma.nGO.create({
    data: {
      userId: ngoUser2.id,
      name: 'Rural Health Trust',
      description: 'Mobile medical vans bringing check-ups, medicines and maternal care to remote villages in Karnataka.',
      presidentName: 'Lakshmi Rao',
      regNum: 'KAR/2019/008271',
      address: '42 MG Road, Indiranagar',
      city: 'Bengaluru', state: 'Karnataka', district: 'Bengaluru', pinCode: '560038',
      phone: '9822233344', email: 'info@ruralhealth.demo',
      mission: 'Healthcare that reaches the last village.',
      areaOfWork: 'Healthcare',
      establishedYear: 2017, employees: 19, volunteers: 85,
      status: 'VERIFIED', verifiedAt: new Date()
    }
  });

  // Left pending on purpose, so the admin queue is not empty on first run.
  const ngo3 = await prisma.nGO.create({
    data: {
      userId: ngoUser3.id,
      name: 'Sunrise Welfare Society',
      description: 'Support for elderly people living alone — meals, medicines and weekly home visits.',
      presidentName: 'Anita Sharma',
      regNum: 'TN/2023/001177',
      address: '7 Anna Salai, Teynampet',
      city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai', pinCode: '600018',
      phone: '9833344455', email: 'contact@sunrise.demo',
      mission: 'Dignity and care in old age.',
      areaOfWork: 'Old Age Support',
      establishedYear: 2023, employees: 6, volunteers: 24,
      status: 'PENDING'
    }
  });

  /* -- Documents --------------------------------------------------------- */
  await prisma.nGODocument.createMany({
    data: [
      documentRow(ngo1.id, 'AADHAAR', 'VERIFIED', '234123412346'),
      documentRow(ngo1.id, 'PAN', 'VERIFIED', 'AAATH1234F'),
      documentRow(ngo1.id, 'VOTER_ID', 'VERIFIED', 'ABC1234567'),
      documentRow(ngo1.id, 'GOV_CERTIFICATE', 'VERIFIED'),
      documentRow(ngo2.id, 'AADHAAR', 'VERIFIED', '345234523457'),
      documentRow(ngo2.id, 'PAN', 'VERIFIED', 'BBBRE5678G'),
      documentRow(ngo2.id, 'GOV_CERTIFICATE', 'VERIFIED'),
      // Pending, so there is something in the admin review queue.
      documentRow(ngo3.id, 'AADHAAR', 'PENDING', '456345634568'),
      documentRow(ngo3.id, 'PAN', 'PENDING', 'CCCSW9012H'),
      documentRow(ngo3.id, 'GOV_CERTIFICATE', 'PENDING')
    ]
  });

  /* -- Payment details --------------------------------------------------- */
  await prisma.nGOPaymentDetails.createMany({
    data: [
      { ngoId: ngo1.id, upiId: 'hopefoundation@upi', bankAccountName: 'Hope Foundation India', accountNumberLast4: '4821', ifsc: 'HDFC0001234' },
      { ngoId: ngo2.id, upiId: 'ruralhealth@upi', bankAccountName: 'Rural Health Trust', accountNumberLast4: '7733', ifsc: 'ICIC0004455' }
    ]
  });

  /* -- Causes ------------------------------------------------------------ */
  await prisma.nGOCause.createMany({
    data: [
      { ngoId: ngo1.id, category: 'Free Education' },
      { ngoId: ngo1.id, category: 'Free Food' },
      { ngoId: ngo1.id, category: 'Child Welfare' },
      { ngoId: ngo2.id, category: 'Medical Support' },
      { ngoId: ngo2.id, category: 'Women Empowerment' },
      { ngoId: ngo3.id, category: 'Old Age Support' }
    ]
  });

  /* -- Activity photos --------------------------------------------------- */
  const activities = [
    { ngo: ngo1, title: 'Free food distribution', description: 'Distributed food packages to 150 families in Lodhi Colony.', category: 'Free Food', status: 'APPROVED', days: 6 },
    { ngo: ngo1, title: 'New learning centre opened', description: 'A third after-school centre opened, serving 60 more children.', category: 'Free Education', status: 'APPROVED', days: 20 },
    { ngo: ngo2, title: 'Village health camp', description: 'Free check-ups and medicines for 210 people across four hamlets.', category: 'Medical Support', status: 'APPROVED', days: 11 },
    // Pending, so the admin has a photo to approve during a demo.
    { ngo: ngo2, title: 'Maternal care workshop', description: 'Training session for 40 expectant mothers on nutrition and care.', category: 'Women Empowerment', status: 'PENDING', days: 2 }
  ];

  for (const a of activities) {
    const file = writePlaceholder(a.ngo.id, `activity-${a.title.replace(/\W+/g, '-')}`, 'png');
    await prisma.nGOActivity.create({
      data: {
        ngoId: a.ngo.id,
        title: a.title,
        description: a.description,
        category: a.category,
        imagePath: file.storagePath,
        activityDate: new Date(Date.now() - a.days * 86400000),
        status: a.status
      }
    });
  }

  /* -- Donations --------------------------------------------------------- */
  const donations = [
    { ngo: ngo1, amount: 5000, category: 'Free Education', ref: 'UPI2026081412345', days: 9 },
    { ngo: ngo1, amount: 2500, category: 'Free Food', ref: 'UPI2026081523456', days: 6 },
    { ngo: ngo2, amount: 10000, category: 'Medical Support', ref: 'UPI2026081634567', days: 3 }
  ];

  let prevHash = GENESIS_HASH;
  for (let i = 0; i < donations.length; i++) {
    const d = donations[i];
    const blockNumber = i + 1;
    const txnId = `TXN-20260814-${crypto.randomBytes(6).toString('hex').toUpperCase()}`;
    const timestamp = new Date(Date.now() - d.days * 86400000);

    const currentHash = BlockchainService.calculateHash({
      blockNumber, prevHash, txnId, amount: d.amount,
      donorId: donor.id, ngoId: d.ngo.id, projectId: null, timestamp
    });

    const block = await prisma.blockchainBlock.create({
      data: {
        blockNumber, prevHash, currentHash, txnId, amount: d.amount,
        donorId: donor.id, ngoId: d.ngo.id, projectId: null, timestamp
      }
    });

    await prisma.donation.create({
      data: {
        donorId: donor.id, ngoId: d.ngo.id, amount: d.amount,
        category: d.category, purpose: d.category,
        paymentMethod: 'UPI', referenceId: d.ref, paymentStatus: 'SUCCESSFUL',
        txnId, blockId: block.id, date: timestamp
      }
    });

    prevHash = currentHash;
  }

  // One pending donation, so the confirm step can be demonstrated.
  await prisma.donation.create({
    data: {
      donorId: donor.id, ngoId: ngo1.id, amount: 1500,
      category: 'Child Welfare', purpose: 'Child Welfare',
      paymentMethod: 'UPI', paymentStatus: 'PENDING',
      txnId: `TXN-20260817-${crypto.randomBytes(6).toString('hex').toUpperCase()}`
    }
  });

  await prisma.whistleblowerReport.create({
    data: {
      trackingCode: `WB-2026-${crypto.randomBytes(4).toString('hex').toUpperCase()}`,
      category: 'Fake Documents',
      description: 'The registration certificate shown by an organisation in Chennai looks edited around the date field.',
      status: 'SUBMITTED'
    }
  });

  await prisma.auditLog.create({
    data: {
      userId: admin.id, userRole: 'ADMIN', action: 'NGO_DECISION',
      module: 'Verification', recordId: ngo1.id,
      details: 'Hope Foundation India marked VERIFIED'
    }
  });

  await prisma.notification.create({
    data: {
      userId: ngoUser3.id,
      title: 'Your organisation is being reviewed',
      message: 'We have received your registration. An admin will review your documents shortly.',
      type: 'INFO', link: '/ngo'
    }
  });

  for (const n of [ngo1, ngo2, ngo3]) {
    await recomputeScores(n.id);
  }

  console.log(`
  Seeding complete.

  Sign in with:
    Admin   admin@ngocommons.demo     Admin@123
    NGO     ngo@ngocommons.demo       NGO@1234
    NGO     newngo@ngocommons.demo    NGO@1234   (pending — for the approval demo)
    Donor   donor@ngocommons.demo     Donor@123
    Public  public@ngocommons.demo    Public@123
`);
}

main()
  .catch(e => {
    console.error('Seeding failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
